### PR TITLE
Project migrated to Alfresco SDK 2.0 structure

### PR DESCRIPTION
**Pull request by douglascrp**
I don't know if it of your interest, but by using Alfresco SDK project you are able to execute your custom code inside an development Alfresco server.
Another advantage is to be able to package your code as an AMP, which is the official package format supported by Alfresco.
I did this port to be able to test this project, as I'm trying to implement the create document, as asked by @iwkse on the issue #3 

If you accept my pull request, then I think you can move both alfresco and share projects to the project's root.
The alfresco project was created only to allow me to execute a full Alfresco server, since I need the repository part.

### CODE REVIEW

**Comment by douglascrp** [comment]
@cetra3 I was looking at your github page, and i saw you have an alfresco gradle plugin project.
Based on that, I don't think you have the interest to port this project to Maven.
Please, let me know what you think.

**Comment by cetra3** [comment]
@douglascrp Internally we use gradle for building our amps as it's much more discrete and we actually have our own amp creator plugin for gradle here:

https://bitbucket.org/parashift/alfresco-amp-plugin

This is what we use to build this project internally.  I have not updated the `build.gradle` of this project to depend on this amp plugin as it's not available in maven central or jcenter, and we don't have a publicly accessible maven repo set up currently.

_However_: I do see the benefit of being able to build an amp file from maven, without gradle, as well.  If you can recreate a pull request which just includes the `pom.xml`, and not change the folder layout considerably as in this pull request, that would be excellent!

**Comment by cetra3** [comment]
@douglascrp OK for me to close this one?

**Comment by iwkse** [comment]
Hi Cetra,
I would like to ask you if you are somehow forced to use gradle for this project instead of the officially and diffused maven within Alfresco. I believe moving to maven would only let the project improves faster.
Regards

**Comment by cetra3** [comment]
As I mentioned previously I'm not against maven.  It's more just personal choice. Gradle is what we have been using internally to great effect.

I do see the benefit of having a Maven pom file, but this is something I don't have the bandwidth for doing myself at the moment.

**Comment by douglascrp** [comment]
@cetra3 well, I already did that for you.
You can close it if you want, but it would be nice to have my pull request accepted.

**Comment by cetra3** [comment]
There are a few extraneous files in your pull request, which I think are based upon the standard maven template which shouldn't really be included in this project.  As I mentioned before, happy to accept the pull request, but I do need you to clean it up quite a bit before submitting.

**Comment by douglascrp** [comment]
Ah, now I understand.
Yes, that's right... there are some "sample code" created by the use of
alfresco's archetype.
I'm going to perform a cleanup and I'm going to recreate the pull request.

Em seg, 29 de jun de 2015 às 22:14, cetra3 notifications@github.com
escreveu:

**Comment by cetra3** [comment]
I've made a commit to enable maven, so this pull request can close.  Thanks for your help!

**Pull request closed without merging**
